grammar
{
    class
    {
        name:TestCSGrammar
        fun
        {
            ret:int
            name:CX
            return
            {
                vr3
                {
                    V:0
                }
            }
        }
        member1
        {
            Per:public
            type:int
            name:id
        }
        member1
        {
            Per:public
            type:string
            name:name
        }
        fun
        {
            Per:public
            ret:void
            name:Count1
            arg
            {
                type:int
                name:a
            }
        }
        fun
        {
            Per:public
            ret:void
            name:Count0
            arg
            {
                type:int
                name:x1
            }
            arg
            {
                type:string
                name:y2
            }
            exp1
            {
                LE
                {
                    T:int
                    V:a
                }
                RE
                {
                    V:6
                }
            }
            exp1
            {
                LE
                {
                    T:int
                    V:b
                }
                RE
                {
                    V:a
                    R
                    {
                        OP:-
                        VR:4
                    }
                }
            }
            exp1
            {
                LE
                {
                    T:int
                    V:d
                }
                RE
                {
                    V:3
                }
            }
            exp1
            {
                LE
                {
                    T:int
                    V:e
                }
                RE
                {
                    V:10
                    R
                    {
                        OP:*
                        VR:6
                    }
                }
            }
            exp1
            {
                LE:b
                RE
                {
                    V:a
                    R
                    {
                        OP:/
                        VR:b
                    }
                    R
                    {
                        OP:+
                        VR:5
                    }
                    R
                    {
                        OP:*
                        VR:a
                    }
                    R
                    {
                        OP:*
                        VR:b
                    }
                    R
                    {
                        OP:*
                        VR:d
                    }
                    R
                    {
                        OP:/
                        VR:3
                    }
                    R
                    {
                        OP:*
                        VR:e
                    }
                }
            }
            exp2
            {
                LE:d
                OP:+=
                RE
                {
                    V:a
                    R
                    {
                        OP:/
                        VR:b
                    }
                    R
                    {
                        OP:+
                        VR:5
                    }
                    R
                    {
                        OP:*
                        VR:a
                    }
                    R
                    {
                        OP:*
                        VR:b
                    }
                    R
                    {
                        OP:*
                        VR:d
                    }
                    R
                    {
                        OP:/
                        VR:3
                    }
                    R
                    {
                        OP:*
                        VR:e
                    }
                }
            }
        }
        fun
        {
            Per:public
            ret:int
            name:Count3
            arg
            {
                type:int
                name:a
            }
            return
            {
                vr3
                {
                    V:a
                    R
                    {
                        OP:+
                        VR:2
                    }
                }
            }
        }
    }
}
