grammar
{
    class
    {
        name:TestCSGrammar
        member1
        {
            type:int
            name:id
        }
        member1
        {
            type:string
            name:name
        }
        fun
        {
            ret:void
            name:Count1
            arg
            {
                type:int
                name:a
            }
        }
        fun
        {
            ret:void
            name:Count0
            arg
            {
                type:int
                name:x1
            }
            arg
            {
                type:string
                name:y2
            }
            exp
            {
                LE
                {
                    T:int
                    V:a
                }
                RE
                {
                    VL:6
                }
            }
            exp
            {
                LE
                {
                    T:int
                    V:b
                }
                RE
                {
                    VL:a
                    VR
                    {
                        OP:-
                        VR:4
                    }
                }
            }
            exp
            {
                LE
                {
                    T:int
                    V:d
                }
                RE
                {
                    VL:3
                }
            }
            exp
            {
                LE
                {
                    T:int
                    V:e
                }
                RE
                {
                    VL:10
                    VR
                    {
                        OP:*
                        VR:6
                    }
                }
            }
            exp
            {
                LE
                {
                    V:b
                }
                RE
                {
                    VL:a
                    VR
                    {
                        OP:/
                        VR:b
                    }
                    VR
                    {
                        OP:+
                        VR:5
                    }
                    VR
                    {
                        OP:*
                        VR:a
                    }
                    VR
                    {
                        OP:*
                        VR:b
                    }
                    VR
                    {
                        OP:*
                        VR:d
                    }
                    VR
                    {
                        OP:/
                        VR:3
                    }
                    VR
                    {
                        OP:*
                        VR:e
                    }
                }
            }
        }
    }
}
