grammar
{
    package
    {
    }
    message
    {
        name:t_GameZoneProto
        member
        {
            condition:optional
            typename:uint32
            name:zone
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:game
            id:2
        }
    }
    message
    {
        name:t_NewLoginSessionProto
        member
        {
            condition:optional
            typename:uint32
            name:wdLoginID
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:wdGatewayID
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:loginTempID
            id:3
        }
        member
        {
            condition:optional
            typename:bytes
            name:domain
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:wdPort
            id:5
        }
        member
        {
            condition:optional
            typename:t_GameZoneProto
            name:gameZone
            id:6
        }
        member
        {
            condition:optional
            typename:t_GameZoneProto
            name:flatZone
            id:7
        }
        member
        {
            condition:optional
            typename:uint64
            name:accid
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:9
        }
        member
        {
            condition:optional
            typename:uint32
            name:state
            id:10
        }
        member
        {
            condition:optional
            typename:string
            name:name
            id:11
        }
        member
        {
            condition:optional
            typename:bytes
            name:passwd
            id:12
        }
        member
        {
            condition:optional
            typename:bytes
            name:client_ip
            id:13
        }
        member
        {
            condition:optional
            typename:bytes
            name:numpasswd
            id:14
        }
        member
        {
            condition:optional
            typename:bytes
            name:passwd2
            id:15
        }
        member
        {
            condition:optional
            typename:uint32
            name:accSafe
            id:16
        }
        member
        {
            condition:optional
            typename:uint32
            name:wdNetType
            id:17
        }
        member
        {
            condition:optional
            typename:uint32
            name:userType
            id:18
        }
        member
        {
            condition:optional
            typename:uint32
            name:createTime
            id:19
        }
        member
        {
            condition:optional
            typename:uint32
            name:viplevel
            id:20
        }
        member
        {
            condition:optional
            typename:uint32
            name:memlevel
            id:21
        }
        member
        {
            condition:optional
            typename:uint32
            name:annualFlag
            id:22
        }
        member
        {
            condition:optional
            typename:uint32
            name:memberFlag
            id:23
        }
        member
        {
            condition:optional
            typename:uint32
            name:vipFlag
            id:24
        }
        member
        {
            condition:optional
            typename:uint32
            name:microclient
            id:25
        }
        member
        {
            condition:optional
            typename:uint32
            name:qqmember
            id:26
        }
        member
        {
            condition:optional
            typename:uint32
            name:qqyearmember
            id:27
        }
        member
        {
            condition:optional
            typename:uint32
            name:qqlevel
            id:28
        }
        member
        {
            condition:optional
            typename:bytes
            name:openid
            id:29
        }
        member
        {
            condition:optional
            typename:bytes
            name:loginurl
            id:30
        }
    }
    message
    {
        name:t_SelectUserProto
        member
        {
            condition:optional
            typename:uint32
            name:ret
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:taskTempid
            id:2
        }
        member
        {
            condition:optional
            typename:t_GameZoneProto
            name:zone
            id:3
        }
        member
        {
            condition:optional
            typename:uint64
            name:accid
            id:4
        }
        member
        {
            condition:optional
            typename:string
            name:name
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:level
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:onlinetime
            id:7
        }
        member
        {
            condition:optional
            typename:uint32
            name:sex
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:job
            id:9
        }
        member
        {
            condition:optional
            typename:uint32
            name:createtime
            id:10
        }
        member
        {
            condition:optional
            typename:uint32
            name:charid
            id:11
        }
    }
    message
    {
        name:t_MapUserSculptProto
        member
        {
            condition:optional
            typename:uint32
            name:dwHorseID
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwHeadID
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwBodyID
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwlegsID
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwhandsID
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwfeetsID
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwWeaponID
            id:7
        }
    }
    message
    {
        name:t_SelectUserInfoProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:string
            name:name
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:level
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:mapid
            id:5
        }
        member
        {
            condition:optional
            typename:string
            name:mapName
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:country
            id:7
        }
        member
        {
            condition:optional
            typename:uint32
            name:group
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:face
            id:9
        }
        member
        {
            condition:optional
            typename:uint32
            name:hair
            id:10
        }
        member
        {
            condition:optional
            typename:string
            name:countryName
            id:11
        }
        member
        {
            condition:optional
            typename:uint32
            name:bitmask
            id:12
        }
        member
        {
            condition:optional
            typename:uint32
            name:forbidTime
            id:13
        }
        member
        {
            condition:optional
            typename:uint32
            name:zone_state
            id:14
        }
        member
        {
            condition:optional
            typename:uint32
            name:target_zone
            id:15
        }
        member
        {
            condition:optional
            typename:uint32
            name:acceptPK
            id:16
        }
        member
        {
            condition:optional
            typename:t_MapUserSculptProto
            name:sculpt
            id:17
        }
        member
        {
            condition:optional
            typename:uint32
            name:flatZoneID
            id:18
        }
        member
        {
            condition:optional
            typename:uint32
            name:gameZoneID
            id:19
        }
        member
        {
            condition:optional
            typename:uint32
            name:activestar
            id:20
        }
    }
    message
    {
        name:t_stUserInfoUserCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:version
            id:1
        }
        member
        {
            condition:repeated
            typename:t_SelectUserInfoProto
            name:userset
            id:2
        }
    }
    message
    {
        name:t_stCreateSelectUserCmdProto
        member
        {
            condition:optional
            typename:string
            name:strUserName
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:jobType
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:charType
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:country
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:suitType
            id:5
        }
        member
        {
            condition:optional
            typename:string
            name:strPromoterName
            id:6
        }
    }
    message
    {
        name:t_stMobileChannelChatUserCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:dwType
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwSysInfoType
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwCharType
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwCountry
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwVip
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwFromUserTempID
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwChatTime
            id:7
        }
        member
        {
            condition:optional
            typename:string
            name:pstrName
            id:8
        }
        member
        {
            condition:optional
            typename:string
            name:pstrChat
            id:9
        }
    }
    message
    {
        name:MainAttrib
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:string
            name:name
            id:2
        }
        member
        {
            condition:optional
            typename:int32
            name:lv
            id:3
        }
        member
        {
            condition:optional
            typename:int32
            name:heroLvLimit
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:energy
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:energyLimit
            id:6
        }
        member
        {
            condition:optional
            typename:uint64
            name:exp
            id:7
        }
        member
        {
            condition:optional
            typename:uint64
            name:totleExp
            id:8
        }
        member
        {
            condition:optional
            typename:int32
            name:title
            id:9
        }
        member
        {
            condition:optional
            typename:int32
            name:icon
            id:10
        }
        member
        {
            condition:optional
            typename:int32
            name:iconEdage
            id:11
        }
        member
        {
            condition:optional
            typename:uint32
            name:gold
            id:12
        }
        member
        {
            condition:optional
            typename:uint32
            name:money
            id:13
        }
        member
        {
            condition:optional
            typename:uint32
            name:exploit
            id:14
        }
        member
        {
            condition:optional
            typename:uint32
            name:totalpkscore
            id:15
        }
    }
    message
    {
        name:stObjectLocationProto
        member
        {
            condition:optional
            typename:uint32
            name:dwLocation
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:x
            id:2
        }
    }
    message
    {
        name:t_ObjectProto
        member
        {
            condition:optional
            typename:uint32
            name:qwThisID
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwObjectID
            id:2
        }
        member
        {
            condition:optional
            typename:string
            name:strName
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwNum
            id:4
        }
        member
        {
            condition:optional
            typename:stObjectLocationProto
            name:pos
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:lv
            id:6
        }
    }
    message
    {
        name:t_AddObjectInfoProto
        member
        {
            condition:optional
            typename:uint32
            name:byActionType
            id:1
        }
        member
        {
            condition:optional
            typename:t_ObjectProto
            name:obj
            id:2
        }
    }
    message
    {
        name:t_stAddObjectListUnityUserCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:version
            id:1
        }
        member
        {
            condition:repeated
            typename:t_AddObjectInfoProto
            name:userset
            id:2
        }
    }
    message
    {
        name:t_DaySignRwdRecProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:state
            id:2
        }
    }
    message
    {
        name:t_DaySignCmdProto
        member
        {
            condition:repeated
            typename:t_DaySignRwdRecProto
            name:signs
            id:1
        }
    }
    message
    {
        name:t_MailOpenCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:mailid
            id:1
        }
    }
    message
    {
        name:t_MailAddListProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:state
            id:2
        }
        member
        {
            condition:optional
            typename:string
            name:fromname
            id:3
        }
        member
        {
            condition:optional
            typename:string
            name:title
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:accessory
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:createtime
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:endtime
            id:7
        }
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:needmoney
            id:9
        }
    }
    message
    {
        name:t_MailContentProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:string
            name:title
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:accessory
            id:3
        }
        member
        {
            condition:optional
            typename:string
            name:text
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:sendmoney
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:recvmoney
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:sendgold
            id:7
        }
        member
        {
            condition:optional
            typename:uint32
            name:recvgold
            id:8
        }
        member
        {
            condition:optional
            typename:t_ObjectProto
            name:item
            id:9
        }
    }
    message
    {
        name:t_PetSoldierStructProto
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:level
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:star
            id:3
        }
        member
        {
            condition:optional
            typename:uint64
            name:exp
            id:4
        }
        member
        {
            condition:optional
            typename:uint64
            name:nextexp
            id:5
        }
    }
    message
    {
        name:t_SoldierCmdProto
        member
        {
            condition:repeated
            typename:t_PetSoldierStructProto
            name:soldiers
            id:1
        }
    }
    message
    {
        name:t_PetGeneralSkillProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:level
            id:2
        }
    }
    message
    {
        name:t_PetGeneralStructProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:level
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:star
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:deathstate
            id:4
        }
        member
        {
            condition:optional
            typename:uint64
            name:exp
            id:5
        }
        member
        {
            condition:repeated
            typename:t_PetGeneralSkillProto
            name:skillset
            id:6
        }
        member
        {
            condition:optional
            typename:uint64
            name:nextexp
            id:7
        }
        member
        {
            condition:optional
            typename:uint32
            name:pkscore
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:souls
            id:9
        }
        member
        {
            condition:optional
            typename:uint32
            name:armySoliderCount
            id:10
        }
        member
        {
            condition:repeated
            typename:uint32
            name:armyEquips
            id:11
        }
        member
        {
            condition:optional
            typename:t_PetSoldierStructProto
            name:armyInfo
            id:12
        }
        member
        {
            condition:optional
            typename:uint32
            name:nextsouls
            id:13
        }
    }
    message
    {
        name:t_GeneralCmdProto
        member
        {
            condition:repeated
            typename:t_PetGeneralStructProto
            name:generals
            id:1
        }
    }
    message
    {
        name:t_FightSettingProto
        member
        {
            condition:optional
            typename:uint32
            name:adviser
            id:1
        }
        member
        {
            condition:repeated
            typename:uint32
            name:generals
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:mainGeneral
            id:3
        }
    }
    message
    {
        name:t_GeneralSelectSoldierProto
        member
        {
            condition:optional
            typename:uint32
            name:general
            id:1
        }
        member
        {
            condition:repeated
            typename:uint32
            name:soldiers
            id:2
        }
    }
    message
    {
        name:t_stRandNameCmdProto
        member
        {
            condition:optional
            typename:string
            name:name
            id:1
        }
    }
    message
    {
        name:t_stGetRandNameCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:sex
            id:1
        }
    }
    message
    {
        name:t_StudyGeneralSkillProto
        member
        {
            condition:optional
            typename:uint32
            name:general
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:skillid
            id:2
        }
    }
    message
    {
        name:t_OneDungeonProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:enterTimes
            id:2
        }
        member
        {
            condition:optional
            typename:int32
            name:leftTimes
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:occupy
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:star
            id:5
        }
    }
    message
    {
        name:t_AllDungonCmdProto
        member
        {
            condition:repeated
            typename:t_OneDungeonProto
            name:dungeonset
            id:1
        }
    }
    message
    {
        name:t_CompleteQuestCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:result
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:star
            id:3
        }
    }
    message
    {
        name:t_ObjProto
        member
        {
            condition:optional
            typename:uint32
            name:objid
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:objnum
            id:2
        }
    }
    message
    {
        name:t_CompleteQuestRewardCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:money
            id:2
        }
        member
        {
            condition:repeated
            typename:t_ObjProto
            name:itemset
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:exploit
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:generalExp
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:soldierExp
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:captureid
            id:7
        }
        member
        {
            condition:optional
            typename:uint32
            name:completecount
            id:8
        }
    }
    message
    {
        name:t_CaptiveGeneralProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:goodwill
            id:2
        }
    }
    message
    {
        name:t_ALLCaptiveGeneralCmdProto
        member
        {
            condition:repeated
            typename:t_CaptiveGeneralProto
            name:captiveset
            id:1
        }
    }
    message
    {
        name:t_GetOneCaptiveCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
    }
    message
    {
        name:t_UserItemCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:qwthisid
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:num
            id:2
        }
    }
    message
    {
        name:t_DelObjCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:qwthisid
            id:1
        }
    }
    message
    {
        name:t_RefreshObjCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:qwthisid
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:num
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:3
        }
    }
    message
    {
        name:t_MoveObjCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:qwthisid
            id:1
        }
        member
        {
            condition:optional
            typename:stObjectLocationProto
            name:dst
            id:2
        }
    }
    message
    {
        name:t_SplitObjCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:qwthisid
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:qwnewthisid
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:dwnum
            id:3
        }
        member
        {
            condition:optional
            typename:stObjectLocationProto
            name:dst
            id:4
        }
    }
    message
    {
        name:t_TavernInfoProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:lastfreetime
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:needbuynum
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:todayfreetime
            id:4
        }
    }
    message
    {
        name:t_TavernMainInfoCmdProto
        member
        {
            condition:repeated
            typename:t_TavernInfoProto
            name:objs
            id:1
        }
    }
    message
    {
        name:t_RewardObjsProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:num
            id:2
        }
    }
    message
    {
        name:t_TavernBuyObjectCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:repeated
            typename:t_RewardObjsProto
            name:objs
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:needbuynum
            id:3
        }
    }
    message
    {
        name:t_TavernStartBuyCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:isbuyten
            id:2
        }
    }
    message
    {
        name:t_CombindObjCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:generalid
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:qwthisid
            id:3
        }
    }
    message
    {
        name:t_CombineObjReturnCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:generalid
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:qwthisid
            id:3
        }
        member
        {
            condition:optional
            typename:t_ObjectProto
            name:oldobj
            id:4
        }
    }
    message
    {
        name:t_PalaceGetRewardCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:todayget
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:returnresult
            id:2
        }
    }
    message
    {
        name:t_PlayValueUpdayteCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:value
            id:2
        }
    }
    message
    {
        name:t_IndivSortItemProto
        member
        {
            condition:optional
            typename:uint32
            name:oldplace
            id:1
        }
        member
        {
            condition:optional
            typename:string
            name:name
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:charid
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:sex
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:job
            id:5
        }
        member
        {
            condition:optional
            typename:string
            name:septname
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:group
            id:7
        }
        member
        {
            condition:optional
            typename:uint32
            name:vip
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:level
            id:9
        }
        member
        {
            condition:optional
            typename:uint32
            name:value
            id:10
        }
        member
        {
            condition:optional
            typename:uint32
            name:value1
            id:11
        }
    }
    message
    {
        name:t_SortListUserCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:page
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:totalpage
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:pkscore
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:place
            id:5
        }
        member
        {
            condition:repeated
            typename:t_IndivSortItemProto
            name:items
            id:6
        }
    }
    message
    {
        name:t_RequestSortListUserCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:page
            id:2
        }
    }
    message
    {
        name:t_SoldierUpStarCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:index
            id:2
        }
    }
    message
    {
        name:t_GeneralAllEquipsCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:t_ObjectProto
            name:equipone
            id:2
        }
        member
        {
            condition:optional
            typename:t_ObjectProto
            name:equiptwo
            id:3
        }
        member
        {
            condition:optional
            typename:t_ObjectProto
            name:equipthree
            id:4
        }
        member
        {
            condition:optional
            typename:t_ObjectProto
            name:equipfour
            id:5
        }
    }
    message
    {
        name:t_GeneralWearEquipCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:qwthisid
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:action
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:oldthisid
            id:4
        }
    }
    message
    {
        name:t_rqGeneralUseExpBook
        member
        {
            condition:optional
            typename:uint32
            name:itemID
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:count
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:generalID
            id:3
        }
    }
    message
    {
        name:t_rtGeneralUseExpBook
        member
        {
            condition:optional
            typename:uint32
            name:itemID
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:generalID
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:value
            id:3
        }
    }
    message
    {
        name:t_rqEquipArmy
        member
        {
            condition:optional
            typename:uint32
            name:position
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:generalID
            id:2
        }
    }
    message
    {
        name:t_rqGeneralUpStar
        member
        {
            condition:optional
            typename:uint32
            name:generalID
            id:1
        }
    }
    message
    {
        name:t_GenralArmyUpdegreeProto
        member
        {
            condition:optional
            typename:uint32
            name:generalID
            id:1
        }
    }
    message
    {
        name:t_PrimaryQuestStateProto
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:questid
            id:2
        }
        member
        {
            condition:optional
            typename:string
            name:content
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:count
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxcount
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:rewardgold
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:rewardmoney
            id:7
        }
        member
        {
            condition:optional
            typename:t_RewardObjsProto
            name:rewarditem
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:state
            id:9
        }
        member
        {
            condition:optional
            typename:string
            name:nametype
            id:10
        }
        member
        {
            condition:optional
            typename:uint32
            name:icon
            id:11
        }
        member
        {
            condition:optional
            typename:uint32
            name:toDoID
            id:12
        }
        member
        {
            condition:optional
            typename:uint32
            name:toDoChildID
            id:13
        }
    }
    message
    {
        name:t_PrimaryQuestInfoCmdProto
        member
        {
            condition:repeated
            typename:t_PrimaryQuestStateProto
            name:questset
            id:1
        }
    }
    message
    {
        name:t_PrimaryQuestGetRewardCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:questid
            id:2
        }
    }
    message
    {
        name:t_DailyQuestStateProto
        member
        {
            condition:optional
            typename:uint32
            name:questid
            id:1
        }
        member
        {
            condition:optional
            typename:string
            name:content
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:count
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxcount
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:rewardhonor
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:rewardmoney
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:state
            id:7
        }
        member
        {
            condition:optional
            typename:string
            name:nametype
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:icon
            id:9
        }
        member
        {
            condition:optional
            typename:uint32
            name:toDoID
            id:10
        }
        member
        {
            condition:optional
            typename:uint32
            name:toDoChildID
            id:11
        }
    }
    message
    {
        name:t_DailyQuestInfoCmdProto
        member
        {
            condition:repeated
            typename:t_DailyQuestStateProto
            name:questset
            id:1
        }
    }
    message
    {
        name:t_DailyQuestGetRewardCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:questid
            id:1
        }
    }
    message
    {
        name:t_SoldierRenameCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:index
            id:2
        }
        member
        {
            condition:optional
            typename:string
            name:name
            id:3
        }
    }
    message
    {
        name:t_CommonRewardCmdProto
        member
        {
            condition:repeated
            typename:t_RewardObjsProto
            name:itemset
            id:1
        }
    }
    message
    {
        name:t_GeneralGetCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:generalid
            id:1
        }
    }
    message
    {
        name:t_SoldierGetCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:type
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:num
            id:2
        }
    }
    message
    {
        name:t_DungeonChapterStateProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:percentstate
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:completecount
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:totalstar
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:starstate
            id:5
        }
    }
    message
    {
        name:t_DungeonChapterRewardCmdProto
        member
        {
            condition:repeated
            typename:t_DungeonChapterStateProto
            name:chapterdata
            id:1
        }
    }
    message
    {
        name:t_DungeonGetChapterRwdCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:iselite
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:rewardindex
            id:3
        }
    }
    message
    {
        name:t_GuideStepCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:canInterrupt
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:nextID
            id:3
        }
    }
    message
    {
        name:t_GuideCompletedCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
    }
    message
    {
        name:t_DungeonStartAutoQuestProto
        member
        {
            condition:optional
            typename:uint32
            name:questid
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:autoquesttime
            id:2
        }
    }
    message
    {
        name:t_OneAutoQuestRewardCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:time
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:money
            id:2
        }
        member
        {
            condition:repeated
            typename:t_ObjProto
            name:itemset
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:exploit
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:generalExp
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:soldierExp
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:captureid
            id:7
        }
    }
    message
    {
        name:t_DungeonAutoQuestRewardProto
        member
        {
            condition:optional
            typename:uint32
            name:questid
            id:1
        }
        member
        {
            condition:repeated
            typename:t_OneAutoQuestRewardCmdProto
            name:rewardset
            id:2
        }
        member
        {
            condition:repeated
            typename:t_ObjProto
            name:extralitemset
            id:3
        }
    }
    message
    {
        name:t_rqPassChapterReward
        member
        {
            condition:optional
            typename:uint32
            name:chapterID
            id:1
        }
    }
    message
    {
        name:t_rtPassChapterReward
        member
        {
            condition:optional
            typename:uint32
            name:chapterID
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:costEnergy
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:exp
            id:3
        }
        member
        {
            condition:repeated
            typename:t_ObjProto
            name:items
            id:4
        }
    }
    message
    {
        name:t_rqChapterRetreat
        member
        {
            condition:optional
            typename:uint32
            name:chapterID
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:reason
            id:2
        }
    }
    message
    {
        name:t_rtChapterTotalReward
        member
        {
            condition:optional
            typename:uint32
            name:chapterID
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:exp
            id:2
        }
        member
        {
            condition:repeated
            typename:t_ObjProto
            name:items
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:first
            id:4
        }
    }
    message
    {
        name:t_rtFirstChargeReward
        member
        {
            condition:optional
            typename:uint32
            name:firstcharge
            id:1
        }
    }
    message
    {
        name:t_CommonReward
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:state
            id:2
        }
    }
    message
    {
        name:t_rtConsumptionReward
        member
        {
            condition:repeated
            typename:t_CommonReward
            name:data
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:totalgold
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:starttime
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:endtime
            id:4
        }
    }
    message
    {
        name:t_rqGetConsumptionReward
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
    }
    message
    {
        name:t_CommonCountReward
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:gettimes
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxtimes
            id:3
        }
    }
    message
    {
        name:t_rtSingleChargeReward
        member
        {
            condition:repeated
            typename:t_CommonCountReward
            name:data
            id:1
        }
    }
    message
    {
        name:t_rqGetSingleChargeReward
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
    }
    message
    {
        name:t_rtAccuChargeReward
        member
        {
            condition:repeated
            typename:t_CommonReward
            name:data
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:totalcharge
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:starttime
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:endtime
            id:4
        }
    }
    message
    {
        name:t_rqGetAccuChargeReward
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
    }
    message
    {
        name:t_rtSevenDayChargeReward
        member
        {
            condition:optional
            typename:uint32
            name:state
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:totalcharge
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:day
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:starttime
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:endtime
            id:5
        }
    }
    message
    {
        name:t_rtSetTimeReward
        member
        {
            condition:optional
            typename:uint32
            name:state
            id:1
        }
    }
    message
    {
        name:t_SecertCourtRecord
        member
        {
            condition:optional
            typename:uint32
            name:index
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:itemid
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:itemnum
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:curprice
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:oldprice
            id:5
        }
    }
    message
    {
        name:t_HeroShopBatchCmdProto
        member
        {
            condition:repeated
            typename:t_SecertCourtRecord
            name:data
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:needgold
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:buytimes
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:moneytype
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxbuytimes
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:leftrefreshtimes
            id:6
        }
    }
    message
    {
        name:t_GroceryShopBathCmdProto
        member
        {
            condition:repeated
            typename:t_SecertCourtRecord
            name:data
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:needgold
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:buytimes
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:moneytype
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxbuytimes
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:leftrefreshtimes
            id:6
        }
    }
    message
    {
        name:t_ArmyShopBathCmdProto
        member
        {
            condition:repeated
            typename:t_SecertCourtRecord
            name:data
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:needgold
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:buytimes
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:moneytype
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxbuytimes
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:leftrefreshtimes
            id:6
        }
    }
    message
    {
        name:t_BuyShopCmdProto
        member
        {
            condition:optional
            typename:uint32
            name:index
            id:1
        }
    }
    message
    {
        name:t_ArenaPlayer
        member
        {
            condition:optional
            typename:uint32
            name:charid
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:rank
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:lv
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:reward
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:power
            id:5
        }
        member
        {
            condition:optional
            typename:string
            name:name
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:state
            id:7
        }
        member
        {
            condition:optional
            typename:string
            name:word
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:card
            id:9
        }
        member
        {
            condition:repeated
            typename:t_PetGeneralStructProto
            name:generals
            id:10
        }
    }
    message
    {
        name:t_ArenaInfoProto
        member
        {
            condition:optional
            typename:uint32
            name:rank
            id:1
        }
        member
        {
            condition:optional
            typename:string
            name:word
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:score
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:currency
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:leftTimes
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxTimes
            id:6
        }
        member
        {
            condition:optional
            typename:uint32
            name:getRewardLeftTime
            id:7
        }
        member
        {
            condition:optional
            typename:uint32
            name:addTimeGold
            id:8
        }
        member
        {
            condition:optional
            typename:uint32
            name:buyTimes
            id:9
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxBuyTimes
            id:10
        }
        member
        {
            condition:repeated
            typename:uint32
            name:generals
            id:11
        }
        member
        {
            condition:optional
            typename:uint32
            name:worshiptime
            id:12
        }
    }
    message
    {
        name:t_ArenaOpponentsProto
        member
        {
            condition:repeated
            typename:t_ArenaPlayer
            name:data
            id:1
        }
    }
    message
    {
        name:t_OperatorArenaPlayerProto
        member
        {
            condition:optional
            typename:uint32
            name:rank
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:charid
            id:2
        }
    }
    message
    {
        name:t_ArenaRankingRecord
        member
        {
            condition:optional
            typename:uint32
            name:rank
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:charid
            id:2
        }
        member
        {
            condition:optional
            typename:string
            name:name
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:lv
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:power
            id:5
        }
    }
    message
    {
        name:t_ArenaRankingProto
        member
        {
            condition:repeated
            typename:t_ArenaRankingRecord
            name:data
            id:1
        }
    }
    message
    {
        name:t_ArenaFightRecord
        member
        {
            condition:optional
            typename:uint32
            name:charid
            id:1
        }
        member
        {
            condition:optional
            typename:string
            name:name
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:lv
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:action
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:delta
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:time
            id:6
        }
    }
    message
    {
        name:t_ArenaFightTidingsProto
        member
        {
            condition:repeated
            typename:t_ArenaFightRecord
            name:data
            id:1
        }
    }
    message
    {
        name:t_AreaShopBathCmdProto
        member
        {
            condition:repeated
            typename:t_SecertCourtRecord
            name:data
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:needgold
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:buytimes
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:moneytype
            id:4
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxbuytimes
            id:5
        }
        member
        {
            condition:optional
            typename:uint32
            name:leftrefreshtimes
            id:6
        }
    }
    message
    {
        name:t_ArenaRankingRewardsPtoro
        member
        {
            condition:optional
            typename:uint32
            name:leagueCurrency
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:leagueMoney
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:count
            id:3
        }
        member
        {
            condition:optional
            typename:uint32
            name:maxcount
            id:4
        }
    }
    message
    {
        name:t_AreaScoreRewards
        member
        {
            condition:repeated
            typename:t_CommonReward
            name:data
            id:1
        }
    }
    message
    {
        name:t_rqGetArenaScoreReward
        member
        {
            condition:optional
            typename:uint32
            name:id
            id:1
        }
    }
    message
    {
        name:t_ArenaAlterWordProto
        member
        {
            condition:optional
            typename:string
            name:word
            id:1
        }
    }
    message
    {
        name:t_ArenaGeneralSettingProto
        member
        {
            condition:repeated
            typename:uint32
            name:generals
            id:1
        }
    }
    message
    {
        name:t_ChallengeArenaPlayerProto
        member
        {
            condition:optional
            typename:uint32
            name:rank
            id:1
        }
        member
        {
            condition:optional
            typename:uint32
            name:charid
            id:2
        }
        member
        {
            condition:optional
            typename:uint32
            name:result
            id:3
        }
    }
}
