grammar
{
    Class
    {
        Name:TestCSGrammar
        Fun
        {
            RET:int
            Name:CX
            Return
            {
                
                {
                    V
                    {
                        V:0
                    }
                }
            }
        }
        Member1
        {
            Per:public
            Type:int
            Name:id
        }
        Member1
        {
            Per:public
            Type:string
            Name:name
        }
        Fun
        {
            Per:public
            RET:void
            Name:Count1
            Argument
            {
                ArgFirst
                {
                    ArgType:int
                    ArgV:a
                }
            }
        }
        Fun
        {
            Per:public
            RET:void
            Name:Count0
            Argument
            {
                ArgFirst
                {
                    ArgType:int
                    ArgV:x1
                }
                ArgTrial
                {
                    ArgType:string
                    ArgV:y2
                }
                ArgTrial
                {
                    ArgType:int
                    ArgV:ppp
                }
                ArgTrial
                {
                    ArgType:string
                    ArgV:jjj
                }
            }
            Exp1
            {
                LeftExp
                {
                    T:int
                    V:a
                }
                RExp
                {
                    RExp
                    {
                        V:6
                    }
                }
            }
            Exp1
            {
                LeftExp
                {
                    T:int
                    V:b
                }
                RExp
                {
                    RExp
                    {
                        V:a
                    }
                    RExp
                    {
                        OP3-:-
                        RExp
                        {
                            RExp
                            {
                                V:4
                            }
                        }
                    }
                }
            }
            Exp1
            {
                LeftExp
                {
                    T:int
                    V:d
                }
                RExp
                {
                    RExp
                    {
                        V:3
                    }
                }
            }
            Exp1
            {
                LeftExp
                {
                    T:int
                    V:e
                }
                RExp
                {
                    RExp
                    {
                        V:6
                    }
                    RExp
                    {
                        OP4*:*
                        RExp
                        {
                            RExp
                            {
                                V:6
                            }
                        }
                    }
                }
            }
            Exp1
            {
                VL:b
                RExp
                {
                    RExp
                    {
                        V:a
                    }
                    RExp
                    {
                        OP4/:/
                        RExp
                        {
                            RExp
                            {
                                V:b
                            }
                            RExp
                            {
                                OP3+:+
                                RExp
                                {
                                    RExp
                                    {
                                        V:5
                                    }
                                    RExp
                                    {
                                        OP4*:*
                                        RExp
                                        {
                                            RExp
                                            {
                                                V:a
                                            }
                                            RExp
                                            {
                                                OP4*:*
                                                RExp
                                                {
                                                    RExp
                                                    {
                                                        V:b
                                                    }
                                                    RExp
                                                    {
                                                        OP4*:*
                                                        RExp
                                                        {
                                                            RExp
                                                            {
                                                                V:d
                                                            }
                                                            RExp
                                                            {
                                                                OP4/:/
                                                                RExp
                                                                {
                                                                    RExp
                                                                    {
                                                                        V:3
                                                                    }
                                                                    RExp
                                                                    {
                                                                        OP4*:*
                                                                        RExp
                                                                        {
                                                                            RExp
                                                                            {
                                                                                V:e
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        Fun
        {
            Per:public
            RET:int
            Name:Count3
            Argument
            {
                ArgFirst
                {
                    ArgType:int
                    ArgV:a
                }
            }
            Return
            {
                
                {
                    V
                    {
                        V:a
                    }
                    
                    {
                        OP3+:+
                        
                        {
                            V
                            {
                                V:2
                            }
                        }
                    }
                }
            }
        }
    }
}
